// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe2663Bjcs8iEPU83xoZ-tKMAAs6YqdzM',
    appId: '1:1038135200519:web:eed9cce6f18e3eb83413a2',
    messagingSenderId: '1038135200519',
    projectId: 'oriontaapp',
    authDomain: 'oriontaapp.firebaseapp.com',
    storageBucket: 'oriontaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_gvKbgAjDg6AS0a9JMDRX1VcdECwo9g',
    appId: '1:1038135200519:android:7d8ac39a0dcf47fa3413a2',
    messagingSenderId: '1038135200519',
    projectId: 'oriontaapp',
    storageBucket: 'oriontaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLM13NRBs8eU0nvziTUsybenqrrmxmI9w',
    appId: '1:1038135200519:ios:e5d144ec26630cb93413a2',
    messagingSenderId: '1038135200519',
    projectId: 'oriontaapp',
    storageBucket: 'oriontaapp.firebasestorage.app',
    iosBundleId: 'com.example.oriontaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLM13NRBs8eU0nvziTUsybenqrrmxmI9w',
    appId: '1:1038135200519:ios:e5d144ec26630cb93413a2',
    messagingSenderId: '1038135200519',
    projectId: 'oriontaapp',
    storageBucket: 'oriontaapp.firebasestorage.app',
    iosBundleId: 'com.example.oriontaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe2663Bjcs8iEPU83xoZ-tKMAAs6YqdzM',
    appId: '1:1038135200519:web:1eefefe2f3a98ecd3413a2',
    messagingSenderId: '1038135200519',
    projectId: 'oriontaapp',
    authDomain: 'oriontaapp.firebaseapp.com',
    storageBucket: 'oriontaapp.firebasestorage.app',
  );
}
